import { test, expect, chromium } from '@playwright/test';
import { resolve, dirname, basename } from 'node:path';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';

test('quote category updates immediately and persists across reloads', async ({ page }) => {
  await page.goto('/newtab.html');
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('日曆樣式').selectOption('reading');
  await page.getByLabel('每日一句分類').selectOption('sheng-yen');
  await page.keyboard.press('Escape');
  await expect(page.locator('.daily-quote > p')).toHaveText('— 聖嚴法師');
  const quote = await page.locator('.daily-quote blockquote').textContent();
  await page.reload();
  await expect(page.locator('.daily-quote blockquote')).toHaveText(quote!);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await expect(page.getByLabel('每日一句分類')).toHaveValue('sheng-yen');
  await page.getByLabel('每日一句分類').selectOption('negative');
  await page.keyboard.press('Escape');
  await expect(page.locator('.daily-quote > p')).toHaveText(/^— (台灣今日曆・原創|網路流傳)$/);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('每日一句分類').selectOption('classics');
  await page.keyboard.press('Escape');
  await expect(page.locator('.daily-quote > p')).toHaveText(/《(論語|周易)/);
});

test('ChatGPT is added once to existing shortcuts and stays deleted', async ({ page }) => {
  await page.goto('/newtab.html');
  await expect(page.getByRole('link', { name: 'ChatGPT', exact: true })).toHaveAttribute('href', 'https://chatgpt.com/');
  await page.evaluate(() => {
    localStorage.setItem('shortcuts', JSON.stringify([{ id: 'custom', name: '原有網站', url: 'https://example.com/', order: 0 }]));
    localStorage.removeItem('chatgptShortcutAdded');
  });
  await page.reload();
  await expect(page.locator('.shortcut-name')).toHaveText(['原有網站', 'ChatGPT']);
  await page.getByRole('button', { name: '編輯 ChatGPT', exact: true }).click();
  await page.getByRole('button', { name: '刪除', exact: true }).click();
  await page.reload();
  await expect(page.locator('.shortcut-name')).toHaveText(['原有網站']);
});

test('classic layout restores the centered original design and persists', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/newtab.html');
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('日曆樣式').selectOption('classic');
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-style', 'classic');
  const group = (await page.locator('.calendar-clock-group').boundingBox())!;
  expect(Math.abs(group.x + group.width / 2 - 960)).toBeLessThan(1);
  expect(group.width).toBe(556);
  await expect(page.locator('.concept-shell')).toBeHidden();
  await page.screenshot({ path: 'test-results/classic-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByRole('radio', { name: '暗色', exact: true }).check();
  await page.keyboard.press('Escape');
  await expect(page.locator('html')).toHaveClass('dark');
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
});

test('calendar workspace navigates dates and restores other layouts', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.clock.install({ time: new Date('2026-09-21T04:00:00Z') });
  await page.goto('/newtab.html');
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('日曆樣式').selectOption('workspace');
  await page.keyboard.press('Escape');
  await expect(page.locator('#month-view-title')).toHaveText('2026 年 9 月');
  await expect(page.locator('.month-cell')).toHaveCount(30);
  await expect(page.getByRole('navigation', { name: '頁面導覽' })).toHaveCount(0);
  await expect(page.locator('.month-lunar')).toHaveCount(30);
  await expect(page.getByRole('button', { name: '2026-09-21', exact: true }).locator('.month-lunar')).toHaveText('十一');
  await expect(page.getByRole('button', { name: '2026-09-11', exact: true }).locator('.month-lunar')).toHaveText('八月初一');
  expect((await page.locator('#analog-clock').boundingBox())!.width).toBe(140);
  await expect(page.locator('.month-weekday')).toHaveText(['日', '一', '二', '三', '四', '五', '六']);
  expect(await page.getByRole('button', { name: '2026-09-01', exact: true }).evaluate(element => Array.from(element.parentElement!.children).indexOf(element) - 7)).toBe(2);
  await expect(page.getByRole('button', { name: '2026-09-06', exact: true })).toHaveClass(/weekend/);
  await expect(page.getByRole('button', { name: '2026-09-07', exact: true })).not.toHaveClass(/weekend/);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('月曆每週起始日').selectOption('1');
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.locator('.month-weekday')).toHaveText(['一', '二', '三', '四', '五', '六', '日']);
  expect(await page.getByRole('button', { name: '2026-09-01', exact: true }).evaluate(element => Array.from(element.parentElement!.children).indexOf(element) - 7)).toBe(1);
  await expect(page.getByRole('button', { name: '2026-09-06', exact: true })).toHaveClass(/weekend/);
  await expect(page.getByRole('button', { name: '2026-09-07', exact: true })).not.toHaveClass(/weekend/);
  await expect(page.getByRole('button', { name: '2026-09-21', exact: true })).toHaveAttribute('aria-current', 'date');
  await page.getByRole('button', { name: '2026-09-22', exact: true }).click();
  await expect(page.locator('#day')).toHaveText('22');
  await expect(page.locator('#history-heading')).toHaveText('9 月 22 日的歷史');
  await expect(page.locator('#history')).toContainText('伊拉克入侵伊朗');
  for (let i = 0; i < 4; i++) await page.getByRole('button', { name: '下一個月' }).click();
  await expect(page.locator('#month-view-title')).toHaveText('2027 年 1 月');
  await expect(page.locator('.month-cell')).toHaveCount(31);
  await page.getByRole('button', { name: '回到今天' }).click();
  await expect(page.locator('#day')).toHaveText('21');
  await expect(page.locator('#history-heading')).toHaveText('歷史上的今天');
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('日曆樣式').selectOption('reading');
  await page.keyboard.press('Escape');
  await expect(page.locator('#month-view')).toHaveCount(0);
  await expect(page.locator('.daily-quote')).toBeVisible();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-style', 'reading');
  await page.screenshot({ path: 'test-results/reading-desktop.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByLabel('日曆樣式').selectOption('modern');
  await page.keyboard.press('Escape');
  await expect(page.locator('.concept-shell')).toBeHidden();
  await expect(page.locator('main > .calendar-clock-group')).toBeVisible();
  await expect(page.locator('main > .history-section')).toBeVisible();
  await expect(page.locator('body > .todo-note')).toBeVisible();
});

for (const style of ['workspace', 'reading']) {
  test(`${style} supports dark mode, mobile and saved todos`, async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/newtab.html');
    await page.getByRole('button', { name: '開啟外觀設定' }).click();
    await page.getByRole('radio', { name: '暗色', exact: true }).check();
    await page.getByLabel('日曆樣式').selectOption(style);
    await page.keyboard.press('Escape');
    await page.getByLabel('新增待辦事項', { exact: true }).fill('整理工作');
    await page.getByLabel('新增待辦事項', { exact: true }).press('Enter');
    await expect(page.locator('#todo-count')).toHaveText('0 / 1');
    await page.screenshot({ path: `test-results/${style}-dark.png`, fullPage: true });
    await page.setViewportSize({ width: 360, height: 800 });
    await page.reload();
    await expect(page.locator('html')).toHaveAttribute('data-style', style);
    await expect(page.locator('html')).toHaveClass('dark');
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
    await page.locator('#todo-panel summary').click();
    await expect(page.getByRole('checkbox', { name: '整理工作' })).toBeVisible();
    await page.screenshot({ path: `test-results/${style}-mobile.png`, fullPage: true });
  });
}

test('traditional calendar uses a paper layout on desktop and fits mobile', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/newtab.html');
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByRole('radio', { name: '亮色', exact: true }).check();
  await page.getByLabel('日曆樣式').selectOption('traditional');
  await page.keyboard.press('Escape');
  const calendar = (await page.locator('.calendar').boundingBox())!;
  const clock = (await page.locator('#analog-clock').boundingBox())!;
  const note = (await page.locator('.todo-note').boundingBox())!;
  expect(calendar.x + calendar.width).toBeLessThan(clock.x);
  expect(clock.x + clock.width).toBeLessThan(note.x);
  await page.screenshot({ path: 'test-results/traditional-desktop.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByRole('radio', { name: '暗色', exact: true }).check();
  await page.keyboard.press('Escape');
  await page.screenshot({ path: 'test-results/traditional-desktop-dark.png', fullPage: true });
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);
});

test('todo stays in its designed position and ignores old saved coordinates', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/newtab.html');
  await page.evaluate(() => localStorage.setItem('todoPosition', JSON.stringify({ x: 10, y: 700 })));
  await page.reload();
  const note = page.locator('.todo-note');
  const handle = page.locator('#todo-panel summary');
  const original = (await note.boundingBox())!;
  expect(original.x).toBeGreaterThan(1000);
  expect(original.y).toBeLessThan(150);
  await page.mouse.move(original.x + 80, original.y + 20);
  await page.mouse.down();
  await page.mouse.move(original.x - 300, original.y + 180, { steps: 10 });
  await page.mouse.up();
  expect((await note.boundingBox())!.x).toBe(original.x);
  expect((await note.boundingBox())!.y).toBe(original.y);
  await handle.focus();
  await handle.press('Alt+ArrowLeft');
  expect((await note.boundingBox())!.x).toBe(original.x);
  await handle.click();
  await expect(page.locator('#todo-panel')).not.toHaveAttribute('open', '');
  await handle.click();
  await expect(page.locator('#todo-panel')).toHaveAttribute('open', '');
});
test('todos persist, sync across tabs, and retain input on storage failure', async ({ page, context }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.goto('/newtab.html');
  const input = page.getByLabel('新增待辦事項', { exact: true });
  await input.fill('完成今日報告');
  await input.press('Enter');
  await expect(page.locator('#todo-count')).toHaveText('0 / 1');
  await page.getByRole('checkbox', { name: '完成今日報告' }).check();
  await expect(page.locator('#todo-count')).toHaveText('1 / 1');
  await page.reload();
  await expect(page.getByRole('checkbox', { name: '完成今日報告' })).toBeChecked();
  const other = await context.newPage();
  await other.goto('/newtab.html');
  await other.locator('#todo-panel summary').click();
  await other.getByLabel('新增待辦事項', { exact: true }).fill('準備明天資料');
  await other.getByLabel('新增待辦事項', { exact: true }).press('Enter');
  await expect(page.locator('#todo-count')).toHaveText('1 / 2');
  await page.getByRole('button', { name: '刪除待辦：完成今日報告', exact: true }).click();
  await expect(other.locator('#todo-count')).toHaveText('0 / 1');
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
  await input.fill('不能遺失的文字');
  await input.press('Enter');
  await expect(page.locator('#todo-error')).toContainText('無法儲存');
  await expect(input).toHaveValue('不能遺失的文字');
  await expect(page.locator('#todo-count')).toHaveText('0 / 1');
  await page.screenshot({ path: 'test-results/todos.png', fullPage: true });
});

test('analog clock uses Taiwan time and advances its hands', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.clock.install({ time: new Date('2026-09-21T07:30:00Z') });
  await page.clock.pauseAt(new Date('2026-09-21T07:30:00Z'));
  await page.goto('/newtab.html');
  await expect(page.locator('#analog-clock')).toHaveAttribute('aria-label', '台灣時間 15:30:00');
  await expect(page.locator('#digital-clock')).toHaveText('15:30:00');
  await expect(page.locator('#clock-hour')).toHaveAttribute('transform', 'rotate(105 60 60)');
  await expect(page.locator('#clock-minute')).toHaveAttribute('transform', 'rotate(180 60 60)');
  await page.clock.runFor(1000);
  await expect(page.locator('#analog-clock')).toHaveAttribute('aria-label', '台灣時間 15:30:01');
  await expect(page.locator('#digital-clock')).toHaveText('15:30:01');
  await expect(page.locator('#clock-second')).toHaveAttribute('transform', 'rotate(6 60 60)');
  const clock = await page.locator('#analog-clock').boundingBox();
  const calendar = await page.locator('.calendar').boundingBox();
  expect(clock!.x).toBeGreaterThan(calendar!.x + calendar!.width);
  expect(clock!.x + clock!.width).toBeLessThan(1920);
  const note = (await page.locator('.todo-note').boundingBox())!;
  expect(clock!.x + clock!.width).toBeLessThan(note.x);
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(1080);
  await expect(page.getByRole('heading', { name: '歷史上的今天', exact: true })).toBeVisible();
  await expect(page.locator('.history-card')).toHaveCount(3);
  const cards = await page.locator('.history-card').evaluateAll(elements => elements.map(element => {
    const rect = element.getBoundingClientRect();
    return { x: rect.x, y: rect.y, width: rect.width };
  }));
  expect(cards[0].y).toBe(cards[1].y);
  expect(cards[1].y).toBe(cards[2].y);
  expect(cards[0].x + cards[0].width).toBeLessThanOrEqual(cards[1].x + 1);
  expect(cards[1].x + cards[1].width).toBeLessThanOrEqual(cards[2].x + 1);
  await page.screenshot({ path: 'test-results/desktop-clock.png', fullPage: true });
});
test('offline rendering, shortcuts CRUD, keyboard sorting, themes and search', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.clock.install({ time: new Date('2026-09-21T04:00:00Z') });
  await page.goto('/newtab.html');
  await expect(page.locator('#day')).toHaveText('21');
  await expect(page.locator('#lunar')).toContainText('八月十一');
  await expect(page.getByRole('heading', { name: '九二一大地震震動台灣' })).toBeVisible();
  await page.getByRole('button', { name: '新增捷徑', exact: true }).click();
  await page.getByLabel('名稱', { exact: true }).fill('測試網站');
  await page.getByLabel('網址', { exact: true }).fill('javascript:alert(1)');
  await page.locator('#shortcut-form').getByRole('button', { name: '完成' }).click();
  await expect(page.locator('#shortcut-error')).toContainText('HTTP');
  await page.getByLabel('網址', { exact: true }).fill('example.com');
  await page.locator('#shortcut-icon').setInputFiles({ name: 'favicon.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j6i8AAAAASUVORK5CYII=', 'base64') });
  await page.locator('#shortcut-form').getByRole('button', { name: '完成' }).click();
  await expect(page.getByRole('link', { name: '測試網站', exact: true })).toHaveAttribute('href', 'https://example.com/');
  await expect(page.getByRole('link', { name: '測試網站', exact: true }).locator('img')).toHaveAttribute('src', /^data:image\/png;base64,/);
  await page.getByRole('button', { name: '編輯 測試網站', exact: true }).focus();
  await page.keyboard.press('Alt+ArrowLeft');
  await expect(page.locator('.shortcut-name')).toHaveText(['YouTube', 'PChome', 'GitHub', '測試網站', 'ChatGPT']);
  await page.reload();
  await page.getByRole('button', { name: '編輯 測試網站', exact: true }).click();
  await page.getByLabel('名稱', { exact: true }).fill('修改網站');
  await page.locator('#shortcut-form').getByRole('button', { name: '完成' }).click();
  await page.getByRole('button', { name: '編輯 修改網站', exact: true }).click();
  await page.getByRole('button', { name: '刪除', exact: true }).click();
  await expect(page.getByRole('link', { name: '修改網站', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '開啟外觀設定' }).click();
  await page.getByRole('radio', { name: '暗色', exact: true }).check();
  await expect(page.locator('html')).toHaveClass('dark');
  await page.getByLabel('日曆樣式').selectOption('traditional');
  await page.keyboard.press('Escape'); await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-style', 'traditional');
  await expect(page.locator('html')).toHaveClass('dark');
  await page.screenshot({ path: 'test-results/dark-traditional.png', fullPage: true });
  await context.setOffline(true);
  await page.clock.fastForward(24 * 60 * 60 * 1000);
  await expect(page.locator('#day')).toHaveText('22');
  await expect(page.locator('#history')).toContainText('伊拉克入侵伊朗');
  await context.setOffline(false);
  await page.route('https://www.google.com/**', route => route.fulfill({ body: '<html>search</html>', contentType: 'text/html' }));
  await page.getByRole('searchbox').count();
  await page.getByLabel('搜尋 Google', { exact: true }).fill('台灣 & 日曆');
  await page.locator('#search-input').press('Enter');
  await expect(page).toHaveURL(/google.com\/search/);
  expect(new URL(page.url()).searchParams.get('q')).toBe('台灣 & 日曆');
  expect(errors).toEqual([]);
});
test('mobile layout and storage failures', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto('/newtab.html');
  await expect(page.getByRole('button', { name: '新增捷徑', exact: true })).toBeEnabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
  await page.getByRole('button', { name: '新增捷徑', exact: true }).click();
  await page.getByLabel('名稱', { exact: true }).fill('cannot save');
  await page.getByLabel('網址', { exact: true }).fill('example.com');
  await page.locator('#shortcut-form').getByRole('button', { name: '完成' }).click();
  await expect(page.getByRole('status')).toContainText('無法儲存');
  await expect(page.locator('#shortcut-dialog')).toBeVisible();
});
test('packaged MV3 extension loads offline and uses chrome.storage', async () => {
  const profile = await mkdtemp(resolve(tmpdir(), 'taiwan-daily-test-'));
  const extension = resolve('dist');
  const context = await chromium.launchPersistentContext(profile, { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  try {
    const page = await context.newPage();
    const external: string[] = [];
    page.on('request', req => { if (/^https?:/.test(req.url())) external.push(req.url()); });
    await context.setOffline(true);
    await page.goto('chrome://newtab/');
    await expect(page.locator('#day')).not.toBeEmpty();
    await expect(page.getByRole('button', { name: '新增捷徑', exact: true })).toBeEnabled();
    expect(await page.evaluate(() => chrome.runtime.getManifest().permissions)).toEqual(['storage', 'favicon']);
    for (const name of ['YouTube', 'PChome', 'GitHub']) {
      const image = page.getByRole('link', { name, exact: true }).locator('img');
      await expect(image).toBeVisible();
      await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0);
    }
    await page.getByRole('button', { name: '新增捷徑', exact: true }).click();
    await page.getByLabel('名稱', { exact: true }).fill('離線儲存');
    await page.getByLabel('網址', { exact: true }).fill('example.com');
    await page.locator('#shortcut-form').getByRole('button', { name: '完成' }).click();
    await expect(page.getByRole('link', { name: '離線儲存', exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByRole('link', { name: '離線儲存', exact: true })).toBeVisible();
    await page.locator('#todo-panel summary').click();
    await page.getByLabel('新增待辦事項', { exact: true }).fill('離線工作');
    await page.getByLabel('新增待辦事項', { exact: true }).press('Enter');
    await expect(page.locator('#todo-count')).toHaveText('0 / 1');
    expect(await page.evaluate(async () => ((await chrome.storage.local.get('todos')).todos as { text: string }[])[0].text)).toBe('離線工作');
    await page.reload();
    await page.locator('#todo-panel summary').click();
    await expect(page.getByRole('checkbox', { name: '離線工作' })).not.toBeChecked();
    expect(external).toEqual([]);
    await page.screenshot({ path: 'test-results/extension.png', fullPage: true });
  } finally {
    await context.close();
    if (dirname(resolve(profile)) !== resolve(tmpdir()) || !basename(profile).startsWith('taiwan-daily-test-')) throw new Error('Unexpected test profile path');
    await rm(profile, { recursive: true, force: true });
  }
});
